
name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: alpine:latest
    steps:
        uses: actions/checkout@v4
        run: echo "Publicando site..."
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
        uses: actions/deploy-pages@v4